"""empty message

Revision ID: c70db6034625
Revises: 6f1b1ed45321
Create Date: 2025-09-26 23:11:46.485676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70db6034625'
down_revision = '6f1b1ed45321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_character_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_character_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planet_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planet_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_vehicle_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_vehicle_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_vehicle_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('favorite_vehicle_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planet_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorite_planet_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_character_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
